version: 0.2
phases:
  install:
    runtime-versions:
      tomcat: 8.5
      jave: corrretto 11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - httpd install
  post_build:
    commands:
      - echo Build completed on `date`